"""add author to verse_translations

Revision ID: 5f2fc53a0a87
Revises: 6e205d3486ff
Create Date: 2026-03-18 15:29:14.054759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f2fc53a0a87'
down_revision: Union[str, Sequence[str], None] = '6e205d3486ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verse_translations', sa.Column('author', sa.String(), nullable=True))
    op.drop_constraint(op.f('uq_verse_language'), 'verse_translations', type_='unique')
    op.create_unique_constraint('uq_verse_language_author', 'verse_translations', ['verse_id', 'language_code', 'author'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_verse_language_author', 'verse_translations', type_='unique')
    op.create_unique_constraint(op.f('uq_verse_language'), 'verse_translations', ['verse_id', 'language_code'], postgresql_nulls_not_distinct=False)
    op.drop_column('verse_translations', 'author')
    # ### end Alembic commands ###
